---
name: Bump Version
on:
  pull_request:

jobs:
  check-and-bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.JENKINS_GITHUB_PAT }}

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Get PR version
        id: pr_version
        run: |
          PR_VERSION=$(jq -r .version package.json)
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Get main version
        id: main_version
        run: |
          MAIN_VERSION=$(git show main:package.json | jq -r .version)
          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

      - name: Compare and bump if needed
        id: compare
        run: |
          PR_VERSION="${{ steps.pr_version.outputs.pr_version }}"
          MAIN_VERSION="${{ steps.main_version.outputs.main_version }}"

          # Function to compare versions
          version_gt() {
            [ "$(printf '%s\n' "$1" "$2" | sort -V | tail -n1)" = "$1" ] && [ "$1" != "$2" ]
          }

          if version_gt "$PR_VERSION" "$MAIN_VERSION"; then
            echo "PR version ($PR_VERSION) is greater than main ($MAIN_VERSION)."
            echo "should_bump=false" >> $GITHUB_OUTPUT
          else
            # Bump patch version
            IFS='.' read -r MAJOR MINOR PATCH <<< "$MAIN_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "Bumping PR version to $NEW_VERSION"
            jq --arg v "$NEW_VERSION" '.version = $v' package.json > package.json.tmp && mv package.json.tmp package.json
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "should_bump=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push new version (if needed)
        if: steps.compare.outputs.should_bump == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ steps.compare.outputs.new_version }} (auto)"
          git push https://x-access-token:${{ secrets.BUMP_VERSION_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
